# Generated by Django 3.1.2 on 2021-01-11 02:42

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('unique_id', models.CharField(default=apps.core.models.get_unique_id, editable=False, max_length=24, unique=True)),
                ('branches', models.ManyToManyField(to='crm.Branch')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userprofile_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userprofile_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'active',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
