# Generated by Django 3.1.2 on 2021-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210123_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaresource',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
